trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'

- script: |
    bash install_requirements.sh
  displayName: Install dependencies

- script: |
    python scripts/train.py
  workingDirectory: dev
  displayName: Train model

- script: |
    python scripts/register_model.py
  workingDirectory: dev
  displayName: Register model
